apiVersion: v1
kind: Service
metadata:
  name: kc-license-server
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 2345
      name: debug
      protocol: TCP
      targetPort: 2345
  selector:
    app: kc-license-server
  sessionAffinity: None
  type: ClusterIP



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-license-server
spec:
  minReadySeconds: 25
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kc-license-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kc-license-server
    spec:
      containers:
        - image: docker.io/shabrul2451/debuging-go:v0.1
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 2345
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5